### ISSUE TITLE
FX Rate View

### ISSUE THREAD

**Issue by Andrei110901** [Andrei110901/BSD-Project#4]
### Description
This page gives user the option to trade several currencies (USD, EUR, GBP, RON, and CHF).

This page contains the following elements:
- *currency I want to buy* (e.g., EUR)
- *currency I want to sell* (e.g., RON)
- *currency exchange rates for sell/buy actions* (e.g., EUR/RON - buy: 4,6100 / sell: 4,7350)
- *notional* - amount I want to buy/sell (e.g., 1.000.000)
- *tenor* - When the trade will take place (e.g., Now / 1 Month / 3 Months)
- *buy* button
- *sell* button

### Tasks
- [ ] Users must be able to add more currency combinations to the dashboard (EUR/RON, EUR/USD, CHF/USD, etc.)
- [ ] Users must use one currency to buy one of the other currencies.
- [ ] Users should be able to customize some aspects of the User Interface.
