### ISSUE TITLE
Users should customize aspects of the UI

### ISSUE THREAD

**Issue by Andrei110901** [Andrei110901/BSD-Project#8]
### Description
**As a** registered user in [FX Rate View](https://github.com/Andrei110901/BSD-Project/issues/4), **I want** to customize aspects of the UI, **so I can** have a better user experience.

### Task
Make the rate view customizable.

### Acceptance criteria
- [ ] **Given** I am a registered user, **when** I am in [FX Rate View](https://github.com/Andrei110901/BSD-Project/issues/4), **then** I can reorder the existing currency combinations.
- [ ] **Given** I am a registered user, **when** I am in [FX Rate View](https://github.com/Andrei110901/BSD-Project/issues/4), **then** I can resize the rate view.
- [ ] **Given** I am a registered user, **when** I am in [FX Rate View](https://github.com/Andrei110901/BSD-Project/issues/4), **then** I can change the color scheme.
